eventCountTotal=665
eventsRetained=665
eventStreamHash=74967ecb400cbb7f438ca408ac4559be179ec69bf003a67d8db26a5bac310846
eventCapture=FULL
splits=172
deletions=172
migrations=91
insertions=200
dominatedRemovals=24
duplicateRemovals=44
truncations=0
