eventCountTotal=659
eventsRetained=659
eventStreamHash=2472e0ccf79f8ea58fedb02cd44ab097512988d83646ef4ffdd7aedc727b8001
eventCapacity=4096
fullCapture=false
splits=170
deletions=170
migrations=118
insertions=200
dominatedRemovals=19
duplicateRemovals=47
truncations=0
