eventCountTotal=668
eventsRetained=668
eventStreamHash=a9754329be48cb6c10598476e8b061c027ead2aa5853c0f15cabb0324a8b7eef
eventCapacity=4096
fullCapture=false
splits=172
deletions=172
migrations=93
insertions=200
dominatedRemovals=22
duplicateRemovals=43
truncations=0
