eventCountTotal=645
eventsRetained=645
eventStreamHash=5a08c2fec9dad56c008c9d3e9212de2d56891582d57a324c394499c43fc1eec6
eventCapacity=4096
fullCapture=false
splits=159
deletions=159
migrations=81
insertions=200
dominatedRemovals=13
duplicateRemovals=63
truncations=0
