eventCountTotal=667
eventsRetained=667
eventStreamHash=f4ccb89326510477d80b7889b7dba999dd560f673fb4f514fd60eabb57a67cf4
eventCapture=FULL
splits=171
deletions=171
migrations=107
insertions=200
dominatedRemovals=11
duplicateRemovals=52
truncations=0
