eventCountTotal=674
eventsRetained=674
eventStreamHash=6cf8b0aa03638bacb6032dca08178f122ff3c99f2ca3d61b45077b42ce1eaf5e
eventCapacity=4096
fullCapture=false
splits=177
deletions=177
migrations=112
insertions=200
dominatedRemovals=16
duplicateRemovals=40
truncations=0
