eventCountTotal=654
eventsRetained=654
eventStreamHash=de1670b0befe1140a35c830d575a4cf9d71ec4584ca48bf4cd65acb61970d427
eventCapture=FULL
splits=161
deletions=161
migrations=98
insertions=200
dominatedRemovals=12
duplicateRemovals=71
truncations=0
