eventCountTotal=653
eventsRetained=653
eventStreamHash=df96bc7e5a6428347d77b728d9c95ae7d0db95d68ee71d5230026a58e7cb4bc2
eventCapacity=4096
fullCapture=false
splits=167
deletions=167
migrations=104
insertions=200
dominatedRemovals=16
duplicateRemovals=50
truncations=0
