eventCountTotal=668
eventsRetained=668
eventStreamHash=23d9b20e125a9555df9df672b736c0fba09ec3aff6c1bd61df8f3db3d5001f66
eventCapacity=4096
fullCapture=false
splits=176
deletions=176
migrations=117
insertions=200
dominatedRemovals=38
duplicateRemovals=36
truncations=0
