eventCountTotal=647
eventsRetained=647
eventStreamHash=c00c4886b4868afcaafdd1bbdbaea5e4bf819d64f41eb4aa88f6e89a08d95a86
eventCapture=FULL
splits=164
deletions=164
migrations=102
insertions=200
dominatedRemovals=45
duplicateRemovals=47
truncations=0
